dahliakliniken/drgribbe

README.md, src/app/about/page.tsx, src/app/components/navigation/Breadcrumbs.tsx, src/app/layout.tsx, src/app/page.tsx, src/messages/sv.json
Add breadcrumb component
Improve folder structure
=> feat: improve folder structure

public/robots.txt
Add robots.txt that disallows all crawlers
=> chore: add robots.txt

.eslintrc.json, .prettierrc.json, src/app/components/navigation/DropdownMenu.tsx, src/app/components/navigation/Footer.tsx
- Use Image from next
- Fix image size
=> fix: use Next image

src/app/brostoperationer/Brostoperationer.tsx, src/app/components/inputs/ButtonWithIcon.tsx, src/app/components/navigation/DropdownMenu.tsx, src/app/components/surfaces/Accordion.tsx, src/app/components/typography/H3.tsx
- Add accordion component
- Close dropdown menu when click on link
- Close dropdown menu when click outside
=> feat: add Accordion component

src/app/brostoperationer/Brostoperationer.tsx, src/app/components/icons/ChevronIcon.tsx, src/app/components/navigation/DropdownMenu.tsx, src/app/components/surfaces/Accordion.tsx, src/messages/sv.json, tailwind.config.ts
- Add styling on accordion
- Add gradient on dropdown menu
- Add texts for accordion
=> feat: improve styling on accordion, add texts

src/app/brostoperationer/Brostoperationer.tsx, src/app/components/layout/Pillar.tsx, src/app/components/layout/Section.tsx, src/app/components/surfaces/Card.tsx, src/app/components/surfaces/CardCustom.tsx, src/app/components/surfaces/HeaderWithFooter.tsx, src/app/components/surfaces/Li.tsx, src/app/components/surfaces/PriceList.tsx, src/app/components/surfaces/Ul.tsx, src/app/components/typography/H1.tsx, src/app/components/typography/H3.tsx, src/app/garanti/Garanti.tsx, src/app/garanti/page.tsx, src/app/page.tsx, src/app/priser/Priser.tsx, src/messages/sv.json
- Garanti-page
- Components for lists and list-items
- Improve design on menu
=> feat: add Garanti page and new surface components for improved layout

src/app/brostoperationer/Brostoperationer.tsx, src/app/brostoperationer/brostforstoring/Brostforstoring.tsx, src/app/brostoperationer/brostlyft/Brostlyft.tsx, src/app/components/surfaces/HeaderWithFooter.tsx, src/messages/sv.json
- Bröstoperationer
- Bröstlyft
- Bröstförstoring
=> feat: add Brostoperationer and Brostlyft copy

src/app/page.tsx
- New hero image
- Add patient room image to home page
=> feat: update page layout with new hero image and add PatientRoom image

src/app/brostoperationer/fore-och-efter/ForeOchEfter.tsx, src/app/brostoperationer/fore-och-efter/page.tsx, src/data/breastOperationsTreatmentsData.ts, src/messages/sv.json
- Add before and after page
- Add Card in Card list
=> feat: add ForeOchEfter page

src/app/brostoperationer/fore-och-efter/ForeOchEfter.tsx, src/app/fragor-och-svar/FragorOchSvar.tsx, src/app/var-personal/VarPersonal.tsx, src/messages/sv.json
=> feat: add our staff page

src/app/brostoperationer/implantaten/Implantaten.tsx, src/app/components/layout/SpaceContainer.tsx, src/app/components/surfaces/Accordion.tsx, src/app/components/typography/AnchorLink.tsx, src/messages/sv.json
Add accordions on page for `Implants`
=> feat: add accordions

src/app/brostoperationer/implantaten/Implantaten.tsx, src/app/brostoperationer/implantaten/accordionData.tsx, src/app/components/layout/Pillar.tsx, src/app/components/surfaces/Accordion.tsx, src/app/components/surfaces/SimpleCard.tsx, src/app/hud-och-injektioner/HudOchInjektioner.tsx, src/app/hud-och-injektioner/accordionData.tsx, src/messages/sv.json, tailwind.config.ts
- Add copy
- Add coral color to Accordion
- Fix focus within accordion
=> feat: enhance accordion component and layout with new data structure

src/app/brostoperationer/implantaten/Implantaten.tsx, src/app/brostoperationer/implantaten/accordionData.tsx, src/app/components/layout/TreatmentBox.tsx, src/app/components/surfaces/Card.tsx, src/app/components/surfaces/ImageModal.tsx, src/app/components/typography/A.tsx, src/app/components/typography/AnchorLink.tsx, src/app/fragor-och-svar/FragorOchSvar.tsx, src/app/fragor-och-svar/accordionData.tsx, src/app/hud-och-injektioner/HudOchInjektioner.tsx, src/app/hud-och-injektioner/accordionData.tsx, src/app/page.tsx, src/messages/sv.json
- Refractor and simplify accordion data
- Fix bug with focus on open button in Image modal
- Correct text key for accordion
- Fix props in `A`component to reflect how we use them in `P` component
=> refactor: components for improved accessibility and code organization

src/app/boka/Boka.tsx, src/app/brostoperationer/Brostoperationer.tsx, src/app/brostoperationer/brostforminskning/Brostforminskning.tsx, src/app/brostoperationer/brostforstoring/Brostforstoring.tsx, src/app/brostoperationer/brostlyft/Brostlyft.tsx, src/app/brostoperationer/fore-och-efter/ForeOchEfter.tsx, src/app/brostoperationer/implantaten/Implantaten.tsx, src/app/fragor-och-svar/FragorOchSvar.tsx, src/app/garanti/Garanti.tsx, src/app/hud-och-injektioner/HudOchInjektioner.tsx, src/app/layout.tsx, src/app/page.tsx, src/app/priser/Priser.tsx, src/app/var-personal/VarPersonal.tsx
- Move `<main>` to layout
- Fix margin for large screens
=> refactor: move <main> to layout

src/app/components/navigation/DropdownMenu.tsx, tailwind.config.ts
Fix bug with animation running on dropdown menu on first render
=> refactor: simplify DropdownMenu animations and remove unused keyframes

.npmrc, next-sitemap.config.js, package.json, pnpm-lock.yaml
=> feat: add next-sitemap configuration and update package dependencies

package.json, pnpm-lock.yaml, src/app/components/navigation/useLinksData.ts, src/app/components/typography/P.tsx, src/app/hitta-hit/HittaHit.tsx, src/app/hitta-hit/page.tsx, src/messages/sv.json
- Add page for Hitta us
- Add icon library
- Add iframe for google maps
=> feat: add "Hitta hit" page with location details and map integration

src/app/layout.tsx
=> feat: preload hero image for improved loading performance

src/app/components/navigation/DropdownMenu.tsx, src/app/components/surfaces/HeaderWithFooter.tsx, tailwind.config.ts
- Fix animation on footer
- Fix gradient on menu
- Fix background image
=> fix: footer animation

src/app/components/surfaces/Li.tsx, src/app/components/typography/A.tsx, src/app/components/typography/AnchorLink.tsx, src/app/garanti/Garanti.tsx
=> fix: update font sizes for list items and links to improve consistency

src/app/brostoperationer/Brostoperationer.tsx, src/app/brostoperationer/implantaten/Implantaten.tsx, src/app/components/surfaces/Accordion.tsx, src/app/components/surfaces/HeaderWithFooter.tsx, src/app/fragor-och-svar/FragorOchSvar.tsx, src/app/page.tsx, tailwind.config.ts
- Add book-button
- Add background images to implants
- Improve accordions
=> feat: improve pages design

src/app/components/navigation/Breadcrumbs.tsx, src/app/components/surfaces/ExpandableTextBox.tsx, src/app/types.ts, src/utils/determineActiveLinkColor.ts
- Add enums for paths
- Utility function to determine link color
=> feat: dynamically set active link color

src/app/components/surfaces/Testimonial.tsx, src/app/globals.css
=> refactor: simplify Testimonial component and update styles

src/app/components/surfaces/FlippableCard.tsx, src/app/components/surfaces/StaffCard.tsx, src/app/globals.css, src/app/var-personal/VarPersonal.tsx, src/messages/sv.json
=> Add FlippableCard component and update staff display in VarPersonal

src/app/components/surfaces/Ul.tsx, src/app/priser/Priser.tsx, src/messages/sv.json
- Add payment rules to Prices page
=> feat: add payment rules

src/app/components/surfaces/Video.tsx, src/app/page.tsx, src/messages/sv.json
=> feat: add Video component and integrate video playback in the main page

src/app/components/surfaces/Video.tsx, src/app/page.tsx
=> feat: add fade transition effect to Video component

src/app/page.tsx
=> feat: remove unused video component and associated video file

next-sitemap.config.js, public/robots.txt
- Update sitemap config
- Remove robots.tsx as it will be generated by next-sitemap package
=> feat: update sitemap configuration and enable robots.txt generation

src/app/personuppgiftspolicy/accordionData.tsx, src/app/personuppgiftspolicy/personuppgiftspolicy.tsx, src/app/sitemap.ts
- Consolidate policy and rights accordion items in accordionData
- Add policy page to site map
=> refactor: consolidate policy and rights accordion items in accordionData

src/app/components/surfaces/HeaderWithFooter.tsx
- Correct email address in footer
=> fix: update email address in HeaderWithFooter component

src/messages/sv.json
=> fix: correct phone number formatting in Swedish localization

.husky/pre-commit, package.json, pnpm-lock.yaml, src/app/components/layout/TreatmentBox.tsx, src/app/components/surfaces/CardRow.tsx, src/app/components/surfaces/JsonLd.tsx, src/app/components/surfaces/SimpleCard.tsx, src/app/components/surfaces/Testimonial.tsx, src/app/globals.css, src/app/layout.tsx, src/app/page.tsx, src/data/allTreatmentsData.ts, src/data/breastOperationsTreatmentsData.ts, src/messages/sv.json
This pull request introduces several enhancements across multiple components, focusing on accessibility improvements, semantic HTML updates, structured data integration, and localization enhancements. The changes aim to improve user experience, SEO, and code maintainability.
* Updated `alt` attributes in the `TreatmentBox` component to use localized text for better screen reader support. 
* Added `altText` properties to treatment data objects for better accessibility. 
* Replaced `div` elements with `article` in the `CardRow` component for improved semantic structure. * Replaced `div` elements with `section` in the `SimpleCard` component for better semantic usage. 
* Introduced a new `JsonLd` component for adding structured data using JSON-LD, improving SEO. 
* Integrated the `JsonLd` …
=> feat: eseo improvements
